### ISSUE TITLE
DevTools seems to be in the EXE.

### ISSUE THREAD

**Issue by chevycam94** [MAVProxyUser/app.asar#2]
I've taken the app.asar apart, and been digging through it for a while now.  I'm starting to think that the full debug options (aka, parameters, etc), are actually in the "DJI Assistant 2.exe" file itself.  I have yet to be able to take the exe apart enough to pull any parts from it, or find out what all is in it successfully.  Has anyone tried looking in there?

**Comment by MAVProxyUser** [comment]
I've not seen any direct work disassembling the .exe... the is an electron based app... most of the logic will be exposed in the javascript. But yet, at the end of the day the functionality resides in the binaries.
