### ISSUE TITLE
I have made quite a bit of progress...where to chat?

### ISSUE THREAD

**Issue by chevycam94** [MAVProxyUser/app.asar#3]
Video is still processing as of the time of this submission:
https://www.youtube.com/watch?v=U7C_O4OU9uo

Is there a place we can chat about working more on this?  It's up to you if you want that info public or not.  My email is "no SPAM for you"

I've got access to all the DevTools functions, although some are missing their respective plugins, and I have yet to refine this to a more usable state, especially the parameters.

**Comment by MAVProxyUser** [comment]
I just sent  you an invite to https://dji-rev.slack.com/

**Comment by chevycam94** [comment]
Got it.  I'm in.  See you there.
